/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c3560c381e967229cebe7f574dc83d12)
interface __BaseEnv_Env {
	ARTIFACTS: R2Bucket;
	DB: D1Database;
	UPLOAD_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "UPLOAD_TOKEN">> {}
}
